### ISSUE TITLE
Posting with file upload gives 500 error

### ISSUE THREAD

**Issue by webscience2** [Gregwar/Formidable#15]
Having problems using this with file uploads. 

Here is the demo form & associated code. Unfortunately I am getting a 500 Server Error but nothing in the error_log regardless of verbosity of logging. 

test.html
```
<form method="post" enctype="multipart/form-data">
    <input type="file" name="file" />
    <input type="text" name="name" />
    <button type="submit" value="Submit">Submit</button>
</form>
```

test.php 

```
<?php 

error_reporting(E_ALL);
ini_set("display_errors", 1);
include('vendor/autoload.php');

$form = new Gregwar\Formidable\Form('test.html');

$form->handle(function() {
    echo "Form OK!";
}, function($errors) {
    echo "Errors: <br/>";
    foreach ($errors as $error) {
        echo "$error<br />";
    }
});
echo $form;

?>

**Comment by Gregwar** [comment]
I think this was because the bug fixed in b06cceb, implying htmlspecialchars running on objects (causing segfaults)
Thanks for reporting

**Comment by Gregwar** [comment]
I think this should be bug reported to PHP:
https://gist.github.com/Gregwar/9a1b6acc6ac3e9c9311f

**Comment by webscience2** [comment]
thanks so much for the quick fix!

**Comment by Gregwar** [comment]
No problem!
Do not hesitate to give feedbacks and report bugs/feature requests
