### ISSUE TITLE
multiple select is not supported

### ISSUE THREAD

**Issue by oadam** [Gregwar/Formidable#16]
When creating a multiple select, i.e. `<select multiple>`, it is not possible to set the value of the field. The existing code of the `Select` Field supposes that the value is a single string, which cannot match more than 1 `<option>`. 

For the moment I'm using an `<input type="multicheckbox">` as a workaround, but I really wished the multiple select worked so that I could use the [select2 library](https://select2.github.io) to have a searchable input.

If you cannot fix it for now, I've forked the repo and might be able to push it in the coming months.

**Comment by Gregwar** [comment]
Handling that would be great indeed
I can have a look but I cant guarantee when, I dont think this would be very difficult to add

**Comment by Gregwar** [comment]
This should be supported now in master, can you confirm?

**Comment by oadam** [comment]
I've tested and I confirm it is working fine. Thank you very much for your help !
