### ISSUE TITLE
Placeholder: Regexp matches end of line

### ISSUE THREAD

**Issue by falkenber9** [Gregwar/Formidable#18]
File: Parser.php
Line: 223

modify from
while (preg_match('#^(.+){{([^}]+)}}(.+)$#mUsi', $part, $match)) {

to
while (preg_match('#^(.+){{([^}]+)}}(.+)$#Usi', $part, $match)) {

in order to make $match[3] match the entire remaining string. The current version uses the 'm' modifier, causing the '$' operator to match at the end of line. The remaining string, if present, is being lost.

Regards,
Robert

**Comment by Gregwar** [comment]
Fixed, thanks for contributing
