### ISSUE TITLE
Warnings with "Select" field in "multiple" mode

### ISSUE THREAD

**Issue by falkenber9** [Gregwar/Formidable#19]
File: Select.php
Function: getHtml()
Line: 116

Using a select-field in multiple mode with the option "required" set.
This causes the output of php-warnings, when none of the given options are preselected.
This is because $this->value is set to null and in_array(...) expects an array as second parameter instead.

Workaround is removing the option required, but this inserts an empty element at the top of the list, which is not desired in this case.

I have extended the if-condition to fix this case:

            if (!is_null($this->value)
				&& (($this->multiple && in_array($option->getValue(), $this->value))
                  || (!$this->multiple && $option->getValue() == $this->value)))

Regards,
Robert

**Comment by Gregwar** [comment]
Should be fixed, thank you  for reporting
