### ISSUE TITLE
Using placeholder creates odd markup

### ISSUE THREAD

**Issue by leepowellcouk** [Gregwar/Formidable#20]
I'm getting some odd behaviour when using placeholders ... 

**HTML**

    <form>
        <h1>Hello {{ name }}</h1>
        <div>
            <label for="name">Enter your name:</label>
            <input type="text" name="name" id="name" />
        </div>
        <div>
            <label for="age">Enter your age:</label>
            <input type="text" name="age" id="age" />
        </div>
        <button type="submit">Submit</button>
    </form>

**PHP**

    $form = new Gregwar\Formidable\Form('forms/myform.html');
    $form->setPlaceholder("name", "Bob");
    echo $form;

**RESULT**

    <form method="post">
        <h1>Hello Bob</h1>
            <input id="name" type="text" name="name" />
        </div>
        <div>
            <label for="age">Enter your age:</label>
            <input id="age" type="text" name="age" />
        </div>
        <button type="submit">Submit</button>
        <input type="hidden" name="posted_token" value="fd6355e491e82ed91deaf3b42661bf0fb0882065" />
    </form>

**Comment by Gregwar** [comment]
Hello,

What's the problem here?

**Comment by leepowellcouk** [comment]
Hi - the resulting markup is not rendering the first opening `div` or for `label`

**Comment by leepowellcouk** [comment]
This seems to only happen after using a placeholder

**Comment by Gregwar** [comment]
(See #18)

**Comment by leepowellcouk** [comment]
I'm on 1.0.7 via Composer

**Comment by Gregwar** [comment]
Ok
I've just pushed tag `v1.0.8` which includes these commit
You can composer update and it should be fine

**Comment by leepowellcouk** [comment]
👍 Thanks
