### ISSUE TITLE
Sending array from the form without multiple tag

### ISSUE THREAD

**Issue by SlimenTN** [Gregwar/Formidable#21]
Hi, I hope you are doiing well :)
First of all thnx for this component realy usefull
Second I was trying to send an array via the form without using the "multiple" tag but it's not working well
this is my code :
```
Path: <input type="file" name="fiches[0][path]" /><br />
Desc: <input name="fiches[0][desc]" /><br />
Desc2: <input name="fiches[0][descr]" /><br />
```
and this is the result I get when I do `var_dump($form->getvalues())`:
```
'fiches' => 
    array (size=3)
      '0][path' => 
        object(Gregwar\Formidable\Fields\FileField)[180]
          protected 'datas' => 
            array (size=5)
              ...
          protected 'maxsize' => null
          protected 'filetype' => null
          protected 'type' => string 'file' (length=4)
          protected 'name' => string 'fiches' (length=6)
          protected 'index' => string '0][path' (length=7)
          protected 'hook' => null
          protected 'attributes' => 
            array (size=0)
              ...
          protected 'value' => null
          protected 'required' => boolean false
          protected 'regex' => null
          protected 'minlength' => null
          protected 'maxlength' => null
          protected 'prettyname' => null
          protected 'readonly' => boolean false
          protected 'valueChanged' => boolean false
          protected 'constraints' => 
            array (size=0)
              ...
          protected 'mapping' => null
          protected 'language' => 
            object(Gregwar\Formidable\Language\English)[148]
              ...
      '0][desc' => string '' (length=0) //---why empty ?!
      '0][descr' => string '' (length=0) //---why empty ?!
```
The file input has been sent well but the two other inputs it seems that the form doesn't see them !
I hope you help me with this and thnx in advance :)

**Comment by Gregwar** [comment]
Hello
This is indeed not handled well yet by Formidable

Here:
https://github.com/Gregwar/Formidable/blob/master/Fields/Field.php#L250

The fields which are array names are handled, but only of the form `a[b]`, withouth handling the multiple depth of the array

This should be fixed

**Comment by Gregwar** [comment]
I think the Field's `index` attribute (https://github.com/Gregwar/Formidable/blob/master/Fields/Field.php#L23) should be an array representing the indexes instead of a simple value

**Comment by Gregwar** [comment]
(+unit test should be added for this)

**Comment by Gregwar** [comment]
I can do this this week, but if you want to work on it and open a PR i'll review it

**Comment by SlimenTN** [comment]
Thnx for your response, but is the the multiple depth of the array are handlel when I use the "multiple" tag ?
To be honest with you I'm trying to integrate your component with my project where I want to create a form dynamically from an object (something close to symfony's methode to create forms) and I found your component very usefull especailly that you are using Symfony's PropertyAccessor component that's helps access to setters and getters of an object. So that's why I need your work badly and I want to make sure that the multiple depth of array are well handled 👍

**Comment by Gregwar** [comment]
I pushed a commit that should handle these fields
Can you tell me if it's OK for you?

**Comment by SlimenTN** [comment]
Thanks really appreciate your help. I'm at work now when I go home I will try it and tell you the result 😃

**Comment by SlimenTN** [comment]
Hi again :)
I tested it and it's working fine with the "multiple" all fields are well handled
but when I try without "multiple" not working well.
you can try this example yourself and check the result:
```
<form method="post">
    <input type="text" name="title" value="123" />   </br>

    <input type="text" name="p[0][t]" /><input type="file" name="p[0][f]"/><br>
    <input type="text" name="p[1][t]" /><input type="file" name="p[1][f]"/><br>
    <input type="submit" value="send  "/>
</form>
```

When I use `var_dump($form->getValues())` this is what I get:

```
array (size=2)
  'title' => string '123' (length=3)
  'p' => 
    array (size=2)
      0 => 
        array (size=1) // it says that the size is 1 but it should be 2 !
          'f' => 
            object(Gregwar\Formidable\Fields\FileField)[171] // input type="file" are handled
              ...
      1 => 
        array (size=1)
          'f' => 
            object(Gregwar\Formidable\Fields\FileField)[173]// input type="file" are handled
```

Inputs type="file" are handled but not the other inputs !

**Comment by SlimenTN** [comment]
I noticed another thing
when I used the multiple tag on input file only it does not handle them (try these examples):

```
<multiple name="fiches" mapping="fiches">
             <input type="text" name="path" mapping="path" /><br />                                
</multiple> 
$form->getValues()['fiches']) gives you a full array (well handled)
```

```
<multiple name="fiches" mapping="fiches">
             <input type="text" name="path" mapping="path" /><br />       
             <input type="file" name="path" mapping="path" /><br />                           
</multiple>
$form->getValues()['fiches']) gives you a full array (well handled)
```

```
<multiple name="fiches" mapping="fiches">
              <input type="file" name="path" mapping="path" /><br />                                
</multiple> 
$form->getValues()['fiches']) gives you an empty array !!
```

**Comment by Gregwar** [comment]
Hello,
There was indeed a mistake in my previous commit, I fixed it, can you give it a try?
I also did a fix for the multiple containing file only, can you check it out?

**Comment by SlimenTN** [comment]
Well done 👍 
now it's working fine and all inputs are well handled 
Thnx for your time and soon as I upload my project I will tell you 😄 
Have a good day.

**Comment by Gregwar** [comment]
Thanks for reporting
