### ISSUE TITLE
Form does not consider new fields

### ISSUE THREAD

**Issue by SlimenTN** [Gregwar/Formidable#22]
Hi again :)
When I created a javascript funtion that add new fields (without using the "multiple" tag that generates fields dynamically), and then sent them, the form doesn't see them, I took a look at your code and I think that the problem might be in the `seValues()` function in `Form.php` line 244:

```
foreach ($this->getFields() as $name => $field) {
//---fill data here 
}
```

Here you loop through the fields that already parsed by the form (before sending data) and fill them with values without checking if there is new fields added to the form (via javascrip for example).

**Comment by Gregwar** [comment]
Hello,
This is normal, the form have to know the fields that are present to check for posted values
What is your use case?

**Comment by SlimenTN** [comment]
Let's say we have this form
```
<form>
     Title: <input type="text" name="title" /><br>
     Description: <textarea name="description" ></textarea><br>
     <div id="newFields">
            <!--New fields goes here-->
     </div>
     <button value="Add new document" id="add" />
</form>
```
and this is a js code to generate new fields:
```
<script>
    var COUNTER = 100;
    jQuery(document).ready(function(){
        $('#add').click(function (e) {
            $('#newFields').append('Document title: <input type="text" name="docTitle['+COUNTER+']" /><br>');
            COUNTER++;
        });
    });
</script>
```
After sending form both title and discritpion are handled but not the case for the new added fields.
when you do `var_dump($form->getValues())` you find only the title and the discription.

**Comment by Gregwar** [comment]
Why don't you use a multiple here?

**Comment by SlimenTN** [comment]
is it customizable ?
I mean can I change the add and remove button and style them ?
cause they are generated automatically by the form itself.

**Comment by Gregwar** [comment]
It could become customalizable
I think that would be the good way

**Comment by Gregwar** [comment]
What is the list of what you want to customize

Le sam. 29 oct. 2016 18:27, Grégoire Passault <g.passault@gmail.com> a
écrit :

**Comment by SlimenTN** [comment]
just the "multiple" tag for now

**Comment by Gregwar** [comment]
Ok, but you mean the add and remove ui and the script, right?

**Comment by SlimenTN** [comment]
yes exactly

**Comment by chippyash** [comment]
@SlimenTN Is this issue still relevant or can it be closed?
