### ISSUE TITLE
MulticheckboxField getValue and setValue are incompatible.

### ISSUE THREAD

**Issue by TimothyBJacobs** [Gregwar/Formidable#25]
Unless I'm mistaken, the `MulticheckboxField::get_value()` and `MulticheckboxField::set_value()` functions seem to be incompatible with each other. That is, I have to reformat my values before passing them to the form. Specifically I have to flip the result.

Input:
```
[ 'option1' => 1, 'option2' => 1 ]
```
Output:
```
[ 0 => 'option1', 1 => 'option2' ]
```

`::getValue()` makes the most sense to me, so `::setValue()` should be updated. Perhaps, to avoid a BC break, `::setValue()` can detect if an associative array if being used and use the current functionality, and if a numerically indexed array is used, use the `::getValue()` format.

Happy to submit a patch if this sounds right to you.

**Comment by Gregwar** [comment]
Hello,

Yes, you are right
I accept the PR if you do it!

**Comment by Gregwar** [comment]
Also note that the current setValue behavior should remain, not because of BC but because this is actually the array your browser send through POST
