### ISSUE TITLE
No phpunit specified in composer

### ISSUE THREAD

**Issue by chippyash** [Gregwar/Formidable#29]
Hi
You should specify the phpunit dependency and version in require-dev in composer.  Just forked your lib to make some changes (and a PR to you,) but don't know which version of phpunit you are using.

In the meantime, can you tell me which version you are using please?

Thanks.

**Comment by Gregwar** [comment]
My own version is still 4.7
However, if you have a look at the travis build, you will find out that many of them seems to works, so you could pick up any of those

**Comment by chippyash** [comment]
Thanks for info. Travis file doesn't tell me which phpunit version it is using. The travis logs suggest they are using 4.8 by default. I know from bitter experience that phpunit testing can break between major versions, so best to actively include the version you want in the dev require so you know it will run.

**Comment by chippyash** [comment]
phpunit now specified
