### ISSUE TITLE
<select><option ... is not processed correctly

### ISSUE THREAD

**Issue by tolgaulas** [Gregwar/Formidable#33]
The below code:
```
    <select name="colour">
        <option value="blue">Blue</option><br />
        <option selected value="red">Red</option><br />
        <option value="green">Green</option><br />
    </select>

```
is displayed as

```
    <select name="" >
<option selected="selected" value=""></option>
<option selected="selected" value=""></option>
<option selected="selected" value="">BlueRedGreen</option>
</select>
```

also, the examples/multiple.php is not displayed correctly.

**Comment by Gregwar** [comment]
Should be fixed now
Can you open another issue with more details for your problem with `multiple.php`?

**Comment by tolgaulas** [comment]
Hi again,

Unfortunately, it's still there.. I've made a cloud9 environment to share. Here is the result : https://formidabletest-tolgaulas.c9users.io and here is the public editor: https://ide.c9.io/tolgaulas/formidabletest

**Comment by Gregwar** [comment]
Are you sure you pulled master?

**Comment by Gregwar** [comment]
I did a tag, now should be `v1.1.2`

**Comment by Gregwar** [comment]
(Actually I think this was a regression bug that was introduced at some point)

**Comment by tolgaulas** [comment]
Yes. Now it works ok with v1.1.2
