### ISSUE TITLE
lazy parse

### ISSUE THREAD

**Issue by tolgaulas** [Gregwar/Formidable#34]
Hi, can we (if we can, how?) pass the form content (file or string) after the class initiation. I instantiate the class in another class and later on populate/use it on it's childs. At the time of construction, the content/file is not present but later on it's introduced. May be what i need is beyond the formidable's context.

**Comment by Gregwar** [comment]
I dont understand the use case for this, but technically this could be done

**Comment by chippyash** [comment]
@tolgaulas Is this issue still relevant or can it be closed?

**Comment by tolgaulas** [comment]
Yes please. Thank you.

Tolga Ulas
+90 533 7464908, skypeid:tolgaulas
