### ISSUE TITLE
Option to return callback result from handle()

### ISSUE THREAD

**Issue by drewm** [Gregwar/Formidable#36]
At the moment, the `Form::handle()` method returns an array of errors. If there are no errors, the array is empty.

If a callback for success or error is passed in, it's executed but the result is discarded. If the callback does anything interesting, it's hard to then control logic flow through your code.

What would you think to adding a third boolean argument to `handle()` that says the return value of the callbacks should be returned to the calling code? This would maintain backwards compatibility (defaulting to false), but provide a flexible option for those who want it.

Happy to submit a PR.

**Comment by Gregwar** [comment]
Hello

Yes, open a pr and I will review it
