### ISSUE TITLE
Support for input type button

### ISSUE THREAD

**Issue by roland-d** [Gregwar/Formidable#37]
Hello,

Thank you for this cool library. I managed quite easily to get it to work but the one issue I am running into is that the input type button is not supported.

My question is, is there any reason why the button type is not supported?

Thank you.

**Comment by Gregwar** [comment]
Hello,
I guess that it would not be really hard to implement indeed, since it doesnt actually affect the server side handling of the form right?

**Comment by roland-d** [comment]
Hey Greg,

I don't see it needs any server side handling because it is a button. This does not require any user input and the value of the button is fixed.

**Comment by chippyash** [comment]
fixed
